from enum import Enum


class RequestStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class RequestType(str, Enum):
    REQUEST_SAFE_STOP = "REQUEST_SAFE_STOP"
    REQUEST_CLEAR_SAFE_STOP = "REQUEST_CLEAR_SAFE_STOP"
    REQUEST_SET_UI_MODE = "REQUEST_SET_UI_MODE"
    REQUEST_ENABLE_AUTO_INTENT = "REQUEST_ENABLE_AUTO_INTENT"
